name: Majunga
favicon: null
layout_spectrum: 0.35839432338252664
typography_spectrum: 0.655630785273388
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.006343606393784285
  lightness: 0.353504077764228
  saturation: 0.613353990484029
  rhythmicContrast: 0.6586579871363938
purpose: []
